language: scala

install:
  - gpg --version

after_script:
- if [[ $TRAVIS_TEST_RESULT == 0 && "$TRAVIS_BRANCH" == "master" ]]; then sbt 'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USER"), System.getenv("SONATYPE_PASS"))' publish; fi
scala:
- 2.11.11
- 2.12.6
jdk:
- oraclejdk8
env:
  global:
  - SONATYPE_USER=mpollmeier
  - secure: ckc8wVBi9QhJErs1MxTukyCVRx76vEaoLEnIjfIUPTMg7qX6NAXTNsPbY6FmI3c2+sL2ljKFyQt5PwIXACQVetkOkmdNYoBDE8njhvIQ21ITupsTSkxDd+bMiUft1r2jhmZYQwXnGIHeX0Pml44eVTci3r8WFt0XZpdCUzE9mxw=
sudo: false
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5c1169757f20f9d27973
    on_success: change
    on_failure: always
    on_start: never   

